### ISSUE TITLE
`ReferenceError: getContent_ is not defined`after exporting library on GAS

### ISSUE THREAD

**Issue by jerrytohvan** [tani/cheeriogs#10]
Hi I'm thinking using your Library to fetch content and perform selector queries from URLs. However, after importing library as instruction I'm still unable to use `getContent_`

**Comment by tani** [comment]
Hi @jerrytohvan . Please try this code instead of `getContent_`.

```js
const r = UrlFetchURL("https://example.com")
const $ = Cheerio.load(r.getContentText())
```

Thanks!
