### ISSUE TITLE
This looks great! Where do I find the methods available?

### ISSUE THREAD

**Issue by lpanebr** [tani/cheeriogs#105]
Is there some documentation or list of methods available?

**Comment by tarasyyyk** [comment]
@lpanebr this repository is just integration (or "wrapper") for Google Apps Script.
You can see details about source package here: https://github.com/cheeriojs/cheerio

**Comment by tani** [comment]
@tarasyyyk Thank you for the explanation. That's right. Please refer to the document of Cheerio.

@lpanebr Thank you for using this library. Have fun!

**Comment by lpanebr** [comment]
thanks @tarasyyyk 
I've found some other examples there:

```js
import { load, select } from 'cheerio';

// Aliases are short hands for longer HTML selectors
select.aliases.classic = 'marquee,blink';

const $ = load(doc);
$(':classic').html();

  ///

const $ = cheerio.load('<div><p></p></div>');

$.contains($('div').get(0), $('p').get(0));
//=> true

$.contains($('p').get(0), $('div').get(0));
//=> false

  ///

const $ = cheerio.load('');

$.merge([1, 2], [3, 4]);
//=> [1, 2, 3, 4]

  ///

const $ = cheerio.load('');
$.parseHTML('<b>markup</b>');

  ///

const $ = cheerio.load('');
$.root();
```
