### ISSUE TITLE
how to work with each element returned by a selection

### ISSUE THREAD

**Issue by rinaldi6109** [tani/cheeriogs#11]
How do I manage each element returned by a selector?

This code works well:
```
  const content = getContent_('https://en.wikipedia.org');
  const $ = Cheerio.load(content);
  Logger.log($('h2').text());
```

But this other one gives me an error:
```
  const content = getContent_('https://en.wikipedia.org');
  const $ = Cheerio.load(content);
  $('h2').each(function(e){Logger.log($(this).text())});
```

What's wrong?

Thank you.

**Comment by tani** [comment]
Sorry for late reply. This library behaves as same as upstream, cheerio, and original works jQuery. You can refer these documents for these instructions. Anyway, I can answer you. Give me a while. I show the example.

**Comment by tani** [comment]
Thank you for asking us but I am sorry to forget it. Do you still have same problem? Please reopen this issue if so.
