### ISSUE TITLE
How to get tag? (updated)

### ISSUE THREAD

**Issue by MaxMor** [tani/cheeriogs#174]
Hi! 
your example: Logger.log($('#mp-right').text());
How to get tag?

Thanks

ps

Does not work : Logger.log($('#mp-right'));

Works :  Logger.log(' ' + $('#mp-right'));

**Comment by tani** [comment]
Hi. Thank you for using this library :)

If you want to get the tag as a raw element: `$('#mp-right').get(0)`.
If you want to just get a name of the tag: `$('#mp-right').prop('tagName')`.
If you want to get the tag as a string: `$('#mp-right').prop('outerHTML')`.
If you want to get the tag as a string without the outermost tag: `$('#mp-right').html()`.

Kind regards,

**Comment by tani** [comment]
Hi. If you have any question and problem, please do not hesitate to reopen this issue. Cheers.
