### ISSUE TITLE
Remove breakpoints

### ISSUE THREAD

**Issue by fragilerus** [tani/cheeriogs#4]
I am using the library directly (no copy) in my project. This has made my project difficult to debug since there appears to be breakpoints in the library, and so the debugger keeps stopping on those remote breakpoints. Please clear?

**Comment by xtaniguchimasaya** [comment]
Thank you for reporting. I'll check it. However, I don't set it. It is curious.

**Comment by larvanitis** [comment]
I confirm this.

![image](https://user-images.githubusercontent.com/1144686/53296553-e6430300-3819-11e9-84af-8df7afe746a8.png)

**Comment by ta2gch** [comment]
Thank you @larvanitis . I try to remove all breakpoints.

**Comment by stubar** [comment]
I am getting this issue also with latest version

**Comment by ta2gch** [comment]
Hello, I made the new version 11 of Google App Scripts for this project.
But it does not solve this issue, of course, there are no breakpoints I set.

@stubar Thank you for giving the idea. I still wonder that...

**Comment by tani** [comment]
Hi there! Google App Script support V8 runtime. Please upgrade your script and this library to version 12.
We can debug as well.
